LD-155 Correct image and instructions for How to update Lucee
lucee/lucee-docs pull request #1285
Opened 2022-08-31 15:20 UTC by gavinbaumanis

Updated the image and instructions for **How to update Lucee**

2022-09-05 11:48 UTC, cfmitrah commented
https://luceeserver.atlassian.net/browse/LD-155

2022-09-08 06:40 UTC, zspitzer commented
@gavinbaumanis why did you remove the section about update providers?

2022-09-08 06:41 UTC, zspitzer requested changes

2022-09-08 06:41 UTC, zspitzer commented on docs/04.guides/03.updating-lucee/01.update/page.md
> -
why did you remove this?

2023-09-19 23:11 UTC, gavinbaumanis commented
Hi @zspitzer 
Just checking in...
AFtewr my explanation...
Do you still want the UPDATE PROVIDERS heading left in?

2023-09-20 13:41 UTC, merged