Precise argument
lucee/lucee-docs pull request #1287
Opened 2022-09-03 12:54 UTC by gavinbaumanis

Updates to the documentation after correcting the grammar / spelling for the new PRECISE argument.

2022-09-05 09:29 UTC, zspitzer commented
@gavinbaumanis we never use master, please use the default branch which is 6.0

2022-09-05 09:33 UTC, zspitzer requested changes

2022-09-05 09:33 UTC, zspitzer commented on docs/03.reference/01.functions/structeach/_arguments/closure.md
> +UDF/Closure that call with the entries from struct
why did you remove the function signature?

2022-09-08 08:04 UTC, closed without merging

2022-09-08 08:06 UTC, gavinbaumanis commented
Just realised I can close my own PR!
This PR is faulty.
I have no idea how 1/2 the files in here got changed - let alone committed and added to the PR.
I will close this PR and submit a new / proper one - if it still needed.